"""empty message

Revision ID: ea437cbd1d8b
Revises: 
Create Date: 2019-12-16 16:58:39.595232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea437cbd1d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False, comment='更新时间'),
    sa.Column('username', sa.String(length=48), nullable=False, comment='用户名'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_create_time'), 'user', ['create_time'], unique=False)
    op.create_index(op.f('ix_user_update_time'), 'user', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_update_time'), table_name='user')
    op.drop_index(op.f('ix_user_create_time'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
